//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InforFilm
    {
        public string MaDon { get; set; }
        public string TenPhim { get; set; }
        public string QuocGia { get; set; }
        public string TheLoai { get; set; }
        public Nullable<System.DateTime> NgayCongChieu { get; set; }
        public Nullable<int> DoTuoiQuyDinh { get; set; }
        public Nullable<double> PTGheDoi { get; set; }
        public Nullable<double> PTDacBiet { get; set; }
        public string HinhAnh { get; set; }
    }
}
